services:
  purewwk:
    image: purewwk:latest
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./appsettings.Development.json:/app/appsettings.Development.json
      - ./appsettings.json:/app/appsettings.json
      - ./Music:/app/Music
      - music_index_vol:/app/music_index
      - hls_segments_vol:/app/hls_segments
    # To run CLI commands:
    # docker-compose run --rm purewwk --rebuild-index
    # docker-compose run --rm purewwk --clear-cache
    # docker-compose run --rm purewwk --help

volumes:
  music_index_vol:
  hls_segments_vol:
